<?php
    $marmitas = array(
        0 => array('id'=>'1', 'nome'=>'Carne Assada ao Molho', 'tamanho'=>'410g','preco'=>'28,30','ingredientes'=>'Creme de Batata [Batata, Leite desnatado zero lactose, Manteiga, Sal], Carne Assada [Carne Bovina, Água, Sal] Molho Madeira [Água, Cebola, Pimenta do Reino, Azeite de Oliva, Carne Bovina, Molho de Tomate [Tomate, Água, Cenoura, Extrato de Tomate, Cebola, Alho Poró, Alho, Sal, Manjericão e Pimenta do Reino), Vinho, Manteiga, Sal e Alho] Legumes Assados [Brócolis, Couve-flor, Cenoura Baby, Vagem, Azeite de oliva extra virgem, Sal, Cúrcuma, Lemon Pepper, Alho em pó, Cebola em pó, Páprica, Orégano]','imagem'=>'img/m1.jpg'),
        1 => array('id'=>'2', 'nome'=>'Picadinho de Carne', 'tamanho'=>'400g','preco'=>'25,90','ingredientes'=>'Picadinho [Carne Bovina, Água, Cenoura, Vinho Tinto, Cebola, Amido de Milho, Azeite de oliva extra virgem, Sal, Alho em pó, Cebola em pó, Manjericão, Alecrim, Folhas de Louro], Arroz Branco [Água, Arroz Branco, Sal , Azeite de oliva extra virgem, Alho], Farofa de Banana da Terra [Farinha de Mandioca, Banana da Terra, Cebola, Manteiga, Alho, Sal ], Salsinha.','imagem'=>'img/m2.jpg'),
        2 => array('id'=>'3', 'nome'=>'VIRADO À PAULISTA', 'tamanho'=>'400g','preco'=>'27,90','ingredientes'=>'Arroz Branco, Tutu de Feijão, Bisteca Acebolada e Couve Manteiga Refogada.','imagem'=>'img/m3.jpg'),
        3 => array('id'=>'4', 'nome'=>'Brasileirinho', 'tamanho'=>'350g','preco'=>'23,90','ingredientes'=>'Feijão Carioca [Água, Feijão carioca, Alho, Azeite de olivia extra virgem, Sal e Louro], Frango Grelhado [Peito de frango, Sal, Azeite de olivia extra virgerm, Alho em pó Cebola em pó],  Arroz Integral [Água, Arroz Integral, Cenoura, Azeite de olivia extra virgem, Alho], Farofa Funcional [Farinha de Mandioca, Cebola, Manteiga, Castanha do Pará, Alho, Cebolinha, Sal, Linhaça].','imagem'=>'img/m4.jpg'),
        4 => array('id'=>'5', 'nome'=>'Strogonoff de Frango', 'tamanho'=>'350g','preco'=>'24,90','ingredientes'=>'Strogonoff de frango [Peito de Frango, Leite semi desnatado zero lactose, Molho Catchup, Amido de milho, Azeite de olivia extra virgem, Sal, Alho em pó, Mostarda, Cebola em pó], Arroz Branco [Água, Arroz Branco, Sal, Óleo, Alho], Batata Rústica Assada [Batata, Azeote de olivia extra virgem, Sal, Alecrim]','imagem'=>'img/m4.jpg'),
        5 => array('id'=>'6', 'nome'=>'Parmeggiana De Frango de Frango', 'tamanho'=>'415g','preco'=>'24,90','ingredientes'=>'Batata Rústica Assada com Alecrim [Batata, Azeite de oliva extra virgem, Sal, Alecrim.], Tiras de Frango Grelhada [Peito de frango, Sal , Azeite de oliva extra virgem, Alho em pó, Cebola em pó], Arroz Branco [ Arroz Branco [Água, Arroz Branco, Sal , Azeite de oliva extra Virgem, Alho] Molho Napoletano [Tomate, Azeite de Oliva extrta Virgem, Cebola, Cenoura, Alho, Mel, Farinha de Arroz, Sal, Manjericão e Pimenta do Reino] Queijo, Mussarela zero Lactose.','imagem'=>'img/m5.jpg'),
        6 => array('id'=>'7', 'nome'=>'Sopa de Queijo com Cebola', 'tamanho'=>'350g','preco'=>'19,71','ingredientes'=>'Ingredientes: Leite zero lactose, água, cebola, manteiga sem sal, queijo tipo muçarela, queijo tipo parmesão, farinha de trigo enrriquecida com ferro e ácido fólico, sal refinado, nóz moscada ."ALÉRGICOS: CONTÉM DERIVADOS DE LEITE DE VACA E DERIVADOS DE TRIGO. PODE CONTER PEIXE, AMENDOIM, CASTANHA DE CAJU, CASTANHA DO BRASIL, NOZES, AMÊNDOAS, DERIVADOS DE SOJA  E OVOS E DERIVADOS DE OVOS". " CONTÉM GLÚTEN". "CONTÉM LACTOSE".','imagem'=>'img/m6.jpg'),
        7 => array('id'=>'8', 'nome'=>'Arroz Carreteiro', 'tamanho'=>'350g','preco'=>'22,41','ingredientes'=>'Água, arroz branco, carne suína (bacon), cebola, tomate, carne bovina (acém), gordura vegetal (óleo de canola), alho, cebolinha e sal refinado. " NÃO CONTÉM GLÚTEN". " ZERO LACTOSE"."ALÉRGICOS: PODE CONTER OVOS, PEIXE, AMENDOIM, CASTANHA DE CAJU, CASTANHA DO BRASIL, NOZES E AMÊNDOAS.','imagem'=>'img/m7.jpg'),
    );
    ?>
